name: Isort

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: PyCQA/isort@stable
        with:
          args: ". --check --profile black"
